spring.application.name=citizen-reporting

# JDBC URL for SQL Server
spring.datasource.url = jdbc:sqlserver://localhost:1433;databaseName=InfrafixDB;encrypt=true;trustServerCertificate=true

# Database Credentials
spring.datasource.username=sa
spring.datasource.password=Password.

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

